# Generated by Django 3.1.5 on 2022-01-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumun_t',
            name='jumun_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
