# Generated by Django 3.1.5 on 2022-02-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumun', '0003_auto_20220126_1448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jumun_T',
        ),
    ]
