# Generated by Django 3.1.5 on 2022-02-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jumun', '0004_delete_jumun_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='jumun_T',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_flag', models.CharField(blank=True, max_length=10, null=True, verbose_name='영문')),
                ('jumun_date', models.CharField(blank=True, max_length=30, null=True, verbose_name='주문일')),
                ('jumun_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='주문ID')),
                ('jumun_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='주문자')),
                ('jumun_con', models.CharField(blank=True, max_length=30, null=True, verbose_name='위탁자')),
                ('brand', models.CharField(blank=True, max_length=30, null=True, verbose_name='브랜드')),
                ('prd_name', models.TextField(blank=True, null=True, verbose_name='상품명')),
                ('prd_color', models.TextField(blank=True, null=True, verbose_name='색상')),
                ('quantity', models.SmallIntegerField(blank=True, null=True, verbose_name='수량')),
                ('wholesale', models.CharField(blank=True, max_length=30, null=True, verbose_name='중도매')),
                ('whole_pr', models.CharField(blank=True, max_length=30, null=True, verbose_name='도매가')),
                ('note', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('sup_pr', models.CharField(blank=True, max_length=30, null=True, verbose_name='공급가')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='이름')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='전화번호')),
                ('address', models.TextField(blank=True, null=True, verbose_name='주소')),
                ('jumun_id2', models.CharField(blank=True, max_length=30, null=True, verbose_name='ID')),
                ('date2', models.CharField(blank=True, max_length=30, null=True, verbose_name='나온날짜')),
            ],
        ),
    ]
