# Generated by Django 3.1.5 on 2022-02-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumun', '0006_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
