# Generated by Django 4.0.1 on 2022-03-03 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumun', '0008_jumunt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jumun_T',
        ),
    ]
