# Generated by Django 4.0.2 on 2022-03-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumun', '0009_delete_jumun_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderT',
            fields=[
                ('order_t_id', models.AutoField(primary_key=True, serialize=False)),
                ('영문', models.CharField(blank=True, max_length=12, null=True)),
                ('주문날짜', models.CharField(blank=True, max_length=45, null=True)),
                ('주문자id', models.CharField(blank=True, db_column='주문자ID', max_length=45, null=True)),
                ('주문자', models.CharField(blank=True, max_length=45, null=True)),
                ('위탁자', models.CharField(blank=True, max_length=45, null=True)),
                ('브랜드', models.CharField(blank=True, max_length=45, null=True)),
                ('상품명', models.CharField(blank=True, max_length=45, null=True)),
                ('색상', models.CharField(blank=True, max_length=255, null=True)),
                ('수량', models.CharField(blank=True, max_length=12, null=True)),
                ('중도매', models.CharField(blank=True, max_length=25, null=True)),
                ('도매가', models.CharField(blank=True, max_length=25, null=True)),
                ('비고', models.CharField(blank=True, max_length=255, null=True)),
                ('공급가', models.CharField(blank=True, max_length=25, null=True)),
                ('이름', models.CharField(blank=True, max_length=45, null=True)),
                ('전화번호', models.CharField(blank=True, max_length=45, null=True)),
                ('주소', models.CharField(blank=True, max_length=255, null=True)),
                ('아이디', models.CharField(blank=True, max_length=45, null=True)),
                ('나온날짜', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': '발송요청',
                'db_table': 'order_t',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='jumunt',
            options={'managed': False, 'verbose_name': '주문장'},
        ),
    ]
